---
- name: add the ib_ipoib module
  modprobe:
    name: ib_ipoib
    state: present
  become: yes
  
- name: setup infiniband nic 
  shell: ifconfig ib0 {{ hostvars[inventory_hostname]['ibip'][inventory_hostname] }}
  become: yes

- name: synchronize source from local directory to remote directories
  synchronize:
    src: "{{ hydra_home }}"
    dest: "{{ hydra_home | dirname }}"